import 'asl_router.dart';
import 'template_store.dart';

class OfflineSentenceService {
  late TemplateStore _store;
  late ASLRouter _router;
  bool _ready = false;

  bool get isReady => _ready;

  Future<void> init() async {
    _store = await TemplateStore.loadFromAsset('assets/templates.json');

    _router = ASLRouter(
      places: const {
        'BATHROOM': 'the restroom',
        'RESTROOM': 'the restroom',
        'TOILET': 'the restroom',
        'WASHROOM': 'the restroom',
        'MEN': "the men's restroom",
        'WOMEN': "the women's restroom",
        'FAMILY': 'the family restroom',
        'ENTRANCE': 'the entrance',
        'EXIT': 'the exit',
        'DOOR': 'the door',
        'LOBBY': 'the lobby',
        'HALL': 'the hallway',
        'HALLWAY': 'the hallway',
        'CORRIDOR': 'the hallway',
        'ROOM': 'the room',
        'OFFICE': 'the office',
        'BUILDING': 'the building',
        'FLOOR': 'this floor',
        'LEVEL': 'this level',
        'ELEVATOR': 'the elevator',
        'LIFT': 'the elevator',
        'STAIRS': 'the stairs',
        'STAIR': 'the stairs',
        'ESCALATOR': 'the escalator',
        'RAMP': 'the ramp',
        'FRONTDESK': 'the front desk',
        'FRONT-DESK': 'the front desk',
        'DESK': 'the front desk',
        'RECEPTION': 'reception',
        'CHECKIN': 'check-in',
        'CHECK-IN': 'check-in',
        'INFORMATION': 'information',
        'INFO': 'information',
        'HELPDESK': 'the help desk',
        'HELP-DESK': 'the help desk',
        'CUSTOMERSERVICE': 'customer service',
        'CUSTOMER-SERVICE': 'customer service',
        'COMMUNITY': 'community',
        'GATE': 'the gate',
        'TERMINAL': 'the terminal',
        'BAGGAGE': 'baggage claim',
        'BAGGAGECLAIM': 'baggage claim',
        'BAGGAGE-CLAIM': 'baggage claim',
        'SECURITY': 'security',
        'SECURITYCHECK': 'security screening',
        'SECURITY-CHECK': 'security screening',
        'TSA': 'security screening',
        'PARKING': 'parking',
        'GARAGE': 'the parking garage',
        'LOT': 'the parking lot',
        'BUSSTOP': 'the bus stop',
        'BUS-STOP': 'the bus stop',
        'STATION': 'the station',
        'TRAINSTATION': 'the train station',
        'TRAIN-STATION': 'the train station',
        'SUBWAY': 'the subway station',
        'CLINIC': 'the clinic',
        'HOSPITAL': 'the hospital',
        'PHARMACY': 'the pharmacy',
        'ER': 'the emergency room',
        'EMERGENCY': 'the emergency room',
        'XRAY': 'X-ray',
        'X-RAY': 'X-ray',
        'RADIOLOGY': 'radiology',
        'IMAGING': 'imaging',
        'CAFE': 'the cafe',
        'CAFETERIA': 'the cafeteria',
        'RESTAURANT': 'the restaurant',
        'FOODCOURT': 'the food court',
        'VENDING': 'the vending machines',
        'ATM': 'the ATM',
        'LOSTFOUND': 'lost and found',
      },
      nouns: const {
        'APPLE': 'apple',
        'BANANA': 'banana',
        'ORANGE': 'orange',
        'GRAPES': 'grapes',
        'WATER': 'water',
        'JUICE': 'juice',
        'SODA': 'soda',
        'COFFEE': 'coffee',
        'TEA': 'tea',
        'FOOD': 'food',
        'SNACK': 'a snack',
        'MEAL': 'a meal',
        'COMMUNITY': 'a community',
        'WIFI': 'Wi-Fi',
        'WI-FI': 'Wi-Fi',
        'INTERNET': 'internet',
        'PASSWORD': 'the password',
        'LOGIN': 'login',
        'ACCOUNT': 'my account',
        'EMAIL': 'email',
        'CHARGER': 'a charger',
        'CABLE': 'a cable',
        'BATTERY': 'battery',
        'PHONE': 'my phone',
        'CELL': 'my phone',
        'MOBILE': 'my phone',
        'LAPTOP': 'my laptop',
        'COMPUTER': 'a computer',
        'TABLET': 'a tablet',
        'TICKET': 'a ticket',
        'PASS': 'a pass',
        'RESERVATION': 'a reservation',
        'CONFIRMATION': 'confirmation',
        'RECEIPT': 'a receipt',
        'REFUND': 'a refund',
        'FORM': 'a form',
        'DOCUMENT': 'a document',
        'PAPER': 'paperwork',
        'ID': 'my ID',
        'LICENSE': 'my ID',
        'PASSPORT': 'my passport',
        'CARD': 'my card',
        'CREDIT': 'a credit card',
        'DEBIT': 'a debit card',
        'CASH': 'cash',
        'MONEY': 'money',
        'PAYMENT': 'a payment',
        'PRICE': 'the price',
        'COST': 'the cost',
        'FEE': 'a fee',
        'WALLET': 'my wallet',
        'BAG': 'my bag',
        'BACKPACK': 'my backpack',
        'PURSE': 'my purse',
        'KEY': 'my key',
        'KEYS': 'my keys',
        'WATCH': 'my watch',
        'GLASSES': 'my glasses',
        'HELP': 'help',
        'ASSIST': 'assistance',
        'ASSISTANCE': 'assistance',
        'SUPPORT': 'support',
        'INTERPRETER': 'an ASL interpreter',
        'TRANSLATOR': 'a translator',
        'CAPTION': 'captions',
        'CAPTIONS': 'captions',
        'DOCTOR': 'a doctor',
        'NURSE': 'a nurse',
        'MEDICINE': 'medicine',
        'PRESCRIPTION': 'a prescription',
        'INSURANCE': 'insurance',
        'PAIN': 'pain',
        'HEADACHE': 'a headache',
        'NAUSEA': 'nausea',
        'ALLERGY': 'an allergy',
        'RIDE': 'a ride',
        'TAXI': 'a taxi',
        'UBER': 'an Uber',
        'LYFT': 'a Lyft',
        'BUS': 'the bus',
        'TRAIN': 'the train',
      },
    );

    _ready = true;
  }

  String generate(List<String> words) {
    if (!_ready) return 'Offline service not ready';

    // Normalize to uppercase — iOS tokenizer sends lowercase
    final upper = words.map((w) => w.toUpperCase()).toList();

    // Truncate to first 3 tokens — router works best with few tokens
    final tokens = upper.length > 3 ? upper.sublist(0, 3) : upper;

    final intentKey = _router.detectIntentKey(tokens);
    final slots = _router.extractSlots(tokens, intentKey);
    final template = _store.pickTemplate(intentKey, slots);
    return renderTemplate(template, slots);
  }
}
